### ISSUE TITLE
Cannot install bpftrace-static and bpftrace-docs

### ISSUE THREAD

**Issue by zenglg** [fbs/el7-bpf-specs#10]
I cannot install bpftrace-static and bpftrace-docs.
Are bpftrace and bpftrace-doc instead of bpftrace-static and bpftrace-docs?

**Comment by fbs** [comment]
Ah docs are out of date,  bpftrace and bpftrace-doc are indeed the packages you need. Thanks

**Comment by fbs** [comment]
fixed in  #11
