### ISSUE TITLE
ERROR: No probe type matched for xxx with bpftrace v0.12.0

### ISSUE THREAD

**Issue by zenglg** [fbs/el7-bpf-specs#14]
(1) Some error info with bpftrace v0.12.0:
```
[root@localhost ~]# uname -r
3.10.0-1127.el7.x86_64
[root@localhost ~]# bpftrace --version
bpftrace v0.12.0
[root@localhost ~]# bpftrace -l '*sleep*'
stdin:1:1-8: ERROR: No probe type matched for *sleep*
*sleep*
~~~~~~~
[root@localhost ~]# 
```

(2) Downgrade bpftace to 0.11.0
```
# yum downgrade bpftrace-0.11.0-5.487dd81.el7.x86_64
```

Now it's OK:
```
[root@localhost ~]# uname -r                                                                               
3.10.0-1127.el7.x86_64
[root@localhost ~]# bpftrace --version                                                                     
bpftrace v0.11.0-225-g487d-dirty
[root@localhost ~]# bpftrace -l '*sleep*'
tracepoint:xfs:xfs_log_grant_sleep
tracepoint:block:block_sleeprq
...
kprobe:ata_sff_busy_sleep
[root@localhost ~]# 
```

**Comment by fbs** [comment]
Probably a regression is bpftrace itself, don't see how my build could break it. 

Hope to release 0.13 and a masterbuild today so I'm going to assume that fixes it

**Comment by zenglg** [comment]
@fbs 
Thank you for your job. 0.13 is worked for me now.

**Comment by zenglg** [comment]
More information:

This issue fixed as below:
https://github.com/iovisor/bpftrace/commit/b7fd0900b18c4b640926e0bb830464565a527ca1

`
Fix single arg wildcard listings
The docs say we can do stuff like

  # bpftrace -l "*sleep*"

so we should probably implement it. We probably regressed on this during
the probe matching refactoring.
`
